version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
      - maria_data:/var/lib/mysql


  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - maria_data:/var/lib/mysql
    

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env

  static_website:
    container_name: static_website
    build: ./requirements/bonus/static_website
    ports:
      - "1337:80"
    restart: always
    volumes:
      - wp_data:/usr/share/nginx/html

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    ports:
      - "9090:9090"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: on-failure

volumes:
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/msekhsou/data/wp_data
  maria_data:
    driver_opts:
      type: none
      o: bind
      device: /home/msekhsou/data/data_base

