services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:msekhsou
    ports: 
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
      - maria_data:/var/lib/mysql
    networks:
      - inception


  mariadb:
    container_name: mariadb
    image: mariadb:msekhsou
    restart: always
    build: 
      context: ./requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PASSWD: ${DB_USER_PASSWD}
        DB_ROOT_PASSWD: ${DB_ROOT_PASSWD}
    env_file:
      - .env
    volumes:
      - maria_data:/var/lib/mysql
    networks:
      - inception
    

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress:msekhsou
    restart: on-failure
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception

  static_website:
    container_name: static_website
    build: ./requirements/bonus/static_website
    image: static_website:msekhsou
    ports:
      - "1337:80"
    restart: always
    volumes:
      - wp_data:/usr/share/nginx/html
    networks:
      - inception

  cadvisor:
    container_name: cadvisor
    build: ./requirements/bonus/cadvisor
    image: cadvisor:msekhsou
    ports:
      - "9090:9090"
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: on-failure
    networks:
      - inception

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    image: redis:msekhsou
  
    restart: always
    networks:
      - inception


  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer
    image: adminer:msekhsou
    ports:
      - "8080:80"
    restart: always
    networks:
      - inception
  
  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    image: ftp:msekhsou
    ports:
      - "21:21"
    restart: always
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    env_file:
      - .env


volumes:
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /home/msekhsou/data/wp_data
  maria_data:
    driver_opts:
      type: none
      o: bind
      device: /home/msekhsou/data/data_base

networks:
  inception:
    driver: bridge