version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    restart: always
    depends_on:
      - wordpress


  mariadb:
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
