version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html


  mariadb:
    container_name: mariadb
    restart: always
    build: ./requirements/mariadb
    ports:
      - "3306:3306"
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    ports:
      - "9000"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - wp_data:/var/www/html
    env_file:
      - .env

volumes:
  wp_data:
    driver_opts:
      type: none
      o: bind
      device: /Users/msekhsou/Desktop/data
